init_project: "Toxric"
init_group: "hepa"
init_notes: "get best hepa run"
dataset: "data/hepa.csv"
seed_idx: 0
epochs: 32
batch_size: 128
lr: 0.0001
testprop: 0.2
input_size: 768
emb_size: 512
# hidden_size: None # 256
# layer_sizes: None # 256,128,64,32,16]
output_size: 1
actfxn: "relu"
linear_type: "ortho"
smilescol: "SMILES"
labelcol: "tox"