init_project: "Multitask_Class_Oral"
init_group: "t_mouse"
init_notes: "split test"
dataset: "oral_data/mouse.csv"
seed_idx: 0
epochs: 0
lr: 0.0001
testprop: 0.2
input_size: 768
emb_size: 256
hidden_size: 256
output_size: 1
layertype: "OrthoLinear"
smilescol: "SMILES"
labelcol: "EPACategoryIndex"
