init_project: "Multitask_Class_Oral"
init_group: "m_mouse"
init_notes: "multi mouse"
dataset: "single_data/mouse"
task: "mouse"
seed_idx: 8
epochs: 32
lr: 0.0001
testprop: 0.2
input_size: 768
emb_size: 256
hidden_size: 256
output_size: 5
layertype: "OrthoLinear"
smilescol: "SMILES"
labelcol: "EPACategoryIndex"
