init_project: "Multitask_Class_Oral"
init_group: "mtask"
init_notes: None
dataset: "oral_data"
task: "all except human"
seed_idx: 8
epochs: 32
lr: 0.0001
testprop: 0.2
input_size: 768
emb_size: 256
hidden_size: 256
output_size: 5
layertype: "OrthoLinear"
smilescol: "SMILES"
labelcol: "EPACategoryIndex"
