program: runscript.py
project: Mouse
name: tree_10_weighted
method: grid
metric:
  name: val f1
  goal: maximize
parameters:
  seed_idx:
    values: [0,1,2,3,4,5,6,7,8,9]
  cutoff:
    value: 10
  model_type:
    value: "tree"
  loss_fxn:
    value: "weighted"
  epochs:
    value: 32
  input_size:
    value: 768
  emb_size:
    value: 256
  hidden_size:
    value: 256
  output_size:
    value: 1
  lr:
    value: 0.0001

