program: runscript_multiclass.py
project: Mouse
name: "multiclass weighted"
method: grid
metric:
  name: "val f1"
  goal: maximize
parameters:
  seed_idx:
    values: [0,1,2,3,4,5,6,7,8,9]
  model_type:
    value: "multiclass"
  loss_fxn:
    value: "weighted"
  epochs:
    value: 32
  input_size:
    value: 768
  emb_size:
    value: 256
  hidden_size:
    value: 256
  output_size:
    value: 5
  lr:
    value: 0.0001

