program: multitask_runscript.py
project: Mouse
name: multitasktree
method: grid
metric:
  name: total_best_ep_f1
  goal: maximize
parameters:
  seed_idx:
    values: [0,1,2,3,4,5,6,7,8,9]
  epochs:
    value: 32
  loss_fxn:
    value: "unweighted"
  input_size:
    value: 768
  emb_size:
    value: 256
  hidden_size:
    value: 256
  output_size:
    value: 1
  lr:
    value: 0.0001

