program: regmulticlass_runscript.py
project: Mouse
name: "regmulticlass_tox"
method: grid
metric:
  name: "val f1"
  goal: maximize
parameters:
  seed_idx:
    values: [0,1,2,3,4,5,6,7,8,9]
  model_type:
    value: "regmulticlass"
  loss_fxn:
    value: "unweighted"
  epochs:
    value: 32
  labelcol:
    value: "tox"
  input_size:
    value: 768
  emb_size:
    value: 256
  hidden_size:
    value: 256
  output_size:
    value: 1
  lr:
    value: 0.0001

